export const FETCH_AVERAGE_RATING_START = 'FETCH_AVERAGE_RATING_START';
export const FETCH_AVERAGE_RATING_SUCCESS = 'FETCH_AVERAGE_RATING_SUCCESS';
export const FETCH_AVERAGE_RATING_FAILED = 'FETCH_AVERAGE_RATING_FAILED';

export const RATE_ARTICLE_START = 'RATE_ARTICLE_START';
export const RATE_ARTICLE_SUCCESS = 'RATE_ARTICLE_SUCCESS';
export const RATE_ARTICLE_FAILED = 'RATE_ARTICLE_FAILED';

export const FETCH_USER_RATING_START = 'FETCH_USER_RATING_START';
export const FETCH_USER_RATING_SUCCESS = 'FETCH_USER_RATING_SUCCESS';
export const FETCH_USER_RATING_FAILED = 'FETCH_USER_RATING_FAILED';
