export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED';

export const FETCH_FOLLOWERS_START = 'FETCH_FOLLOWERS_START';
export const FETCH_FOLLOWERS_COMPLETE = 'FETCH_FOLLOWERS_COMPLETE';

export const UNMOUNT_ARTICLE = 'UNMOUNT_ARTICLE';
